export const INTERSECTION_OBSERVER_THRESHOLD = 0.1;
export const INTERSECTION_OBSERVER_THRESHOLD_FEATURES = 0.08;
export const ANIMATION_DELAYS = {
  STEP: 100,
  HEADER_TEXT: 300,
  IMAGE: 400,
  BUTTONS: 500,
  SUCCESS_BADGE: 1000,
  FEATURE_CARD: 100,
} as const;
